# Generated by Django 3.1.4 on 2020-12-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование ресторана')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=100, verbose_name='Координаты')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.restaurant', verbose_name='Ресторан')),
            ],
        ),
    ]
