# Generated by Django 3.1.4 on 2020-12-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchise',
            options={'verbose_name': 'Франшиза', 'verbose_name_plural': 'Франшизы'},
        ),
    ]
